### ISSUE TITLE
Storage Account - Kind

### ISSUE THREAD

**Issue by ChrisHanna** [dapr/workflows#52]
Really excited about this functionality! 

One thing I ran into when setting up the sample was my storage account "kind" was BlobStorage and the sample would fail, however when I tried with a different storage account  it worked! That one was set to storage/General Purpose.

With BlobStorage - the error would be "Microsoft.WindowsAzure.Storage.StorageException: Unexpected HTTP status code 'NotImplemented'."

![Tip](https://user-images.githubusercontent.com/3343979/85210714-58ddc900-b310-11ea-9848-f109cdb4970c.JPG)

**Comment by laveeshb** [comment]
The reason is that workflow runtime uses table and queue at runtime.
