### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by doddgu** [dapr/workflows#74]
Hi, @yaron2 
We are very interested in this project. If workflows can work under the stand-alone, It will solves our two problems.
1. Build the workflow based on Workflow 2 json.
2. Service aggregation.

**Comment by yaron2** [comment]
Yes the project is maintained. What you described are valid scenarios.

**Comment by doddgu** [comment]
> Yes the project is maintained. What you described are valid scenarios.

OK, Thanks for your reply.
